import {
  Kayano_black,
  Kayano_orange,
  Kayano_red,
  adidas_black,
  adidas_orange,
  adidas_red,
  armour_black,
  armour_orange,
  armour_red,
  foam_black,
  foam_orange,
  foam_red,
  jordon_black,
  jordon_orange,
  jordon_red,
  kinvara_black,
  kinvara_orange,
  // kinvara_red,
  nike_black,
  nike_orange,
  nike_red,
  puma_black,
  puma_orange,
  puma_red,
  rider_black,
  rider_orange,
  rider_red,
} from "../assets";

export const initialProducts = [
  {
    title: "Jordan Proto Lyte",
    collection: "Running Collection",
    description: "Lightweight and breathable, perfect for running.",
    availableColors: ["Red", "Black", "Orange"],
    price: 245,
    productID: 0,
    imageUrl: jordon_red,
    redImageUrl: jordon_red,
    blackImageUrl: jordon_black,
    orangeImageUrl: jordon_orange,
  },
  {
    title: "Nike Air Zoom Pegasus",
    collection: "Running Collection",
    description: "Designed for comfort and performance.",
    availableColors: ["Blue", "White", "Grey"],
    price: 180,
    productID: 1,
    imageUrl: nike_red,
    redImageUrl: nike_red,
    blackImageUrl: nike_black,
    orangeImageUrl: nike_orange,
  },
  {
    title: "Adidas Ultraboost",
    collection: "Running Collection",
    description: "Boost technology for ultimate energy return.",
    availableColors: ["Black", "White", "Green"],
    price: 200,
    productID: 2,
    imageUrl: adidas_red,
    redImageUrl: adidas_red,
    blackImageUrl: adidas_black,
    orangeImageUrl: adidas_orange,
  },
  {
    title: "New Balance Fresh Foam",
    collection: "Running Collection",
    description: "Fresh Foam midsole cushioning for a plush feel.",
    availableColors: ["Red", "Black", "Blue"],
    price: 150,
    productID: 3,
    imageUrl: foam_red,
    redImageUrl: foam_red,
    blackImageUrl: foam_black,
    orangeImageUrl: foam_orange,
  },
  {
    title: "Asics Gel-Kayano",
    collection: "Running Collection",
    description: "High-performance running shoes with GEL technology.",
    availableColors: ["Yellow", "Black", "Orange"],
    price: 160,
    productID: 4,
    imageUrl: Kayano_red,
    redImageUrl: Kayano_red,
    blackImageUrl: Kayano_black,
    orangeImageUrl: Kayano_orange,
  },
  {
    title: "Puma Ignite",
    collection: "Running Collection",
    description: "Engineered for maximum speed and comfort.",
    availableColors: ["Red", "Grey", "Black"],
    price: 130,
    productID: 5,
    imageUrl: puma_red,
    redImageUrl: puma_red,
    blackImageUrl: puma_black,
    orangeImageUrl: puma_orange,
  },
  {
    title: "Brooks Ghost",
    collection: "Running Collection",
    description: "Smooth transitions and soft cushioning for runners.",
    availableColors: ["Blue", "Black", "White"],
    price: 120,
    productID: 6,
    imageUrl: nike_red,
    redImageUrl: nike_red,
    blackImageUrl: nike_black,
    orangeImageUrl: nike_orange,
  },
  {
    title: "Under Armour HOVR",
    collection: "Running Collection",
    description: "HOVR technology provides a zero-gravity feel.",
    availableColors: ["Green", "Black", "Orange"],
    price: 140,
    productID: 7,
    imageUrl: armour_red,
    redImageUrl: armour_red,
    blackImageUrl: armour_black,
    orangeImageUrl: armour_orange,
  },
  {
    title: "Saucony Kinvara",
    collection: "Running Collection",
    description: "Minimalist design with responsive cushioning.",
    availableColors: ["Red", "Yellow", "Black"],
    price: 110,
    productID: 8,
    imageUrl: kinvara_orange,
    redImageUrl: kinvara_orange,
    blackImageUrl: kinvara_black,
    orangeImageUrl: kinvara_orange,
  },
  {
    title: "Mizuno Wave Rider",
    collection: "Running Collection",
    description: "Wave technology for smooth and stable rides.",
    availableColors: ["Black", "White", "Blue"],
    price: 150,
    productID: 9,
    imageUrl: rider_red,
    redImageUrl: rider_red,
    blackImageUrl: rider_black,
    orangeImageUrl: rider_orange,
  },
];
